// Auto-generated by OpenLane
module Survivor_Memory_Unit(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input clk,
  input rst_n,
  input survivor_select_00,
  input survivor_select_01,
  input survivor_select_10,
  input survivor_select_11,
  input[1:0] winner_state,
  output[7:0] decoded_out
);
endmodule
