// Auto-generated by OpenLane
module Maximum_Path_Memory(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input[3:0] prev_00,
  input[3:0] prev_01,
  input[3:0] prev_10,
  input[3:0] prev_11,
  output[1:0] winner_state
);
endmodule
