// Auto-generated by OpenLane
module Branch_Metrics(
`ifdef USE_POWER_PINS
  inout VGND,
  inout VPWR,
`endif
  input[1:0] received,
  output[1:0] bm_00_00,
  output[1:0] bm_00_10,
  output[1:0] bm_01_00,
  output[1:0] bm_01_10,
  output[1:0] bm_10_01,
  output[1:0] bm_10_11,
  output[1:0] bm_11_01,
  output[1:0] bm_11_11
);
endmodule
