// Auto-generated by OpenLane
module Viterbi_Top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input start,
  input[1:0] received,
  output[7:0] decoded_out,
  output frame_done
);
endmodule
